##USEFUL INFORMATION
##MaxViolation: Amount of Times a Player has to fail a Check before he gets punished
##Available Punishments: Cancel, Kick, Ban
##Combat Checks can not have a different Punishment

#Debug

enable-debug: false
config-version: "1.2.0"
prefix: "§f[§eGuardian§f]"
alert-message-debug: "%PREFIX% §c%PLAYER%§f failed §a%CHECK%§a [§4%VIOLATION%§a]"
alert-message: "%PREFIX% §c%PLAYER%§f is using §a%CHECK%"
kick-message: "%PREFIX% §fYou have been Kicked for Cheating!"
ban-message: "%PREFIX% §fYou have been Banned for Cheating!"

#Reach

Reach-notify: true
Maximum-Reach: 3.6
Reach-MaxViolations: 3
Reach-AlertFrequency: 8

#Hitbox

Hitbox-notify: true
Hitbox-MaxViolations: 3
Hitbox-AlertFrequency: 8

#Timer

Timer-notify: true
Timer-MaxViolations: 1
Timer-AlertFrequency: 5
Timer-Punishment: "Cancel"
Timer-TickDifference: 3

#AutoClicker

AutoClicker-notify: true
AutoClicker-MaxViolations: 3
AutoClicker-AlertFrequency: 25
CPS-Limit: 15

#BadPacketsA

BadPacketsA-notify: true
BadPacketsA-MaxViolations: 5
BadPacketsA-AlertFrequency: 10
BadPacketsA-Punishment: "Cancel"

#BadPacketsB

BadPacketsB-notify: true
BadPacketsB-MaxViolations: 5
BadPacketsB-AlertFrequency: 10
BadPacketsB-Punishment: "Cancel"

#ImpossibleRotations

ImpossibleRotations-notify: true
ImpossibleRotations-MaxViolations: 8
ImpossibleRotations-AlertFrequency: 20

#GhostHand

GhostHand-notify: true
GhostHand-MaxViolations: 5
GhostHand-AlertFrequency: 10
GhostHand-Punishment: "Cancel"

#Speed

Speed-notify: true
Speed-MaxViolations: 20
Speed-AlertFrequency: 8
Speed-Punishment: "Cancel"

#Fly

Fly-notify: true
Fly-MaxViolations: 30
Fly-AlertFrequency: 10
Fly-Punishment: "Kick"